# Generated by Django 2.2.7 on 2019-11-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proo',
            name='hhgh',
            field=models.CharField(default='hvhvhbh jgj', max_length=120),
        ),
        migrations.AddField(
            model_name='proo',
            name='real',
            field=models.TextField(default=' tgfgf null', max_length=120),
        ),
    ]
